---
- name: setup etcd
  hosts: all
  become: true
  become_method: sudo

  vars: 
    ansible_python_interpreter: '/usr/bin/env python3'

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - etcd
  
